### ISSUE TITLE
Migrate MNIST Dataset to not use Python

### ISSUE THREAD

**Issue by louisfd** [tracel-ai/burn#1157]
Be able to download MNIST dataset without needing Python. 
Use HF Rust bindings for this specific dataset: #1027 
Change the book to not have to install python at the beginning.

**Comment by laggui** [comment]
As [discussed](https://github.com/tracel-ai/burn/issues/1027#issuecomment-1887727295) in the other issue, turns out MNIST is a great example of a HF hub dataset that only relies on their python config file for the `datasets` library to correctly download and setup the data.

https://huggingface.co/datasets/mnist/blob/main/mnist.py

The `hf-hub` crate is not going to be useful here. The only files available to download in that repo is the python config that will need to be parsed in order to actually download and setup the data.

I'll just use the same data source as their config to download the files, but this won't require the use of the `hf-hub` crate.
