### ISSUE TITLE
Add `argsort` tensor op

### ISSUE THREAD

**Issue by laggui** [tracel-ai/burn#1369]
Maybe also `argsort_descending` for reverse order?

**Example**
```rust
let x = Tensor::from_data([1, 0, 3, 4, -1], &device)
x.argsort(0) // argsort(dim)
// [4, 1, 0, 2, 3]
```

**Comment by louisfd** [comment]
Just looked at https://pytorch.org/docs/stable/generated/torch.argsort.html
- They have the sorting order as parameter, but I think it would be prettier to have two methods like you suggest. But for the sake of simplicity in our backends, it would be great if both methods rely on a single backend operation. 
- They also have a stable option. Is sorting stability something we need to enforce for your use case?

**Comment by laggui** [comment]
Just quickly looked at the code and it looks like `torch.argsort` actually just returns part of the results for [`torch.sort`](https://pytorch.org/docs/stable/generated/torch.sort.html). Do we want to follow a similar pattern (i.e., adding `argsort` would require implementing `sort`)?

For the stable option, my specific use case does not require that the order of equivalent elements is preserved.

**Comment by louisfd** [comment]
Yeah I don't think there's really a way of argsorting without actually sorting at the same time. We have plenty operations that have `with_indices` in their name and return a pair of tensor, one of the element of the input and the other of integer indices. We can follow a similar pattern, and we'll also have the `sort` operation for free. 
Since stability is not necessary, we won't enforce it for now.
