### ISSUE TITLE
docs / add segmentation mask example to burn book

### ISSUE THREAD

**Issue by anthonytorlucci** [tracel-ai/burn#2494]
This is related to the original issue #2361 and pr #2426 . 

Add an example of creating a segmentation mask dataset to the burn book under section 5.9 Dataset ->  Images.

Any guidance from the maintainers would be appreciated. @laggui helped with code reviews in the pull request.

**Comment by laggui** [comment]
This should be relatively straightforward 🙂 

For documentation, a short example similar to the [image classification dataset usage](https://burn.dev/burn-book/building-blocks/dataset.html#images) of the `ImageFolderDataset` could be added.

It is simply meant to show how to create the dataset from a set of items, so you can start with what you added for the unit tests, but with a more relatable theme. Since the classification dataset examples use cats & dogs, you could follow the same path and have classes "cat", "dog" and "background" for example.
