### ISSUE TITLE
Named dimensions for tensors

### ISSUE THREAD

**Issue by veluca93** [Tracel-AI/burn#77]
### Feature description
It would be useful to have "named dimensions" on tensors, i.e. a "Width" dimension for image-like tensors.

### Feature motivation
Many bugs when writing ML models come from improperly mixing dimensions. Being able to name the dimensions, and disallowing mixing them improperly, might significantly reduce the risk of bugs.

### Suggest a Solution
I haven't thought too much about this, but perhaps using tag structs for each dimension might be the way to go, maybe also with a special struct that is const-generic over a `usize` that represents dimensions known at compile time.

**Comment by antimora** [comment]
I am labeling this for a design discussion.

**Comment by nathanielsimard** [comment]
There is an example with an experimental feature flag that tries it here: https://github.com/burn-rs/burn/tree/main/examples/named-tensor.

**Comment by antimora** [comment]
> There is an example with an experimental feature flag that tries it here: https://github.com/burn-rs/burn/tree/main/examples/named-tensor.

Nice interesting work. Now I understand why it's behind the feature flag because it's a new tensor type altogether. 

@nathanielsimard  Have you considered a simpler solution by enhancing Shape struct? We can come up with a macro that generates named fields and give description to the dimension. Shape will remain backward compatible this way.

**Comment by antimora** [comment]
I would say we have this experimental feature. I am closing it done for now.
